### ISSUE TITLE
Invalid config, but all work

### ISSUE THREAD

**Issue by Simonz82** [GuilleGF/hassio-ovh#14]
hello,
I have entered in with in configuration.yaml
this string

```
ovh:
  domain: xxx.xxx.com
  username: myuser
  password: !secret ovh_access (with my psw)
```

everything works perfectly, HA is accessible with nginx etc.
but why do I get these errors ?
how can i solve it ?
  
![2024-09-17_124221](https://github.com/user-attachments/assets/5ddd4a9b-34c9-4ddd-8852-4062c93d8c22)
![2024-09-17_124211](https://github.com/user-attachments/assets/70256787-034b-4969-bbb5-6e090363218e)
